backend:
  name: github
  branch: main
  repo: usrrname/biitsi
  site_domain: cms.netlify.com
  site_url: https://biitsi.org

# global
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: bitsicloud
    api_key: 167316888477451
    multiple: true
media_folder: image/upload
public_folder: static

collections:
  - name: projects
    label: Projects
    label_singular: "Project"
    folder: _projects
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{year}}/{{month}}/{{slug}}"
    path: "{{title}}/index"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: project
      - label: Title
        name: title
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Medium
        name: medium
        widget: string
      - label: Year
        name: year
        widget: datetime
        dateFormat: MM.YYYY
        format: L
      - label: Exhibition or Venue
        name: exhibition
        widget: string
      - label: Curated by
        name: curator
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
      - label: Featured Image
        name: thumbnail
        widget: image

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        create: true
        fields:
          - label: Description
            name: description
            widget: markdown
      - file: src/pages/press/index.md
        label: Press
        name: press
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: File
            name: file
            widget: file
          - label: Tags
            name: tags
            widget: list
