backend:
  name: github
  branch: main
  repo: usrrname/biitsi
  site_url: https://biitsi.org

# global
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: bitsicloud
    api_key: 167316888477451
    multiple: true
media_folder: image/upload
public_folder: static

collections:
  - name: projects
    label: Projects
    label_singular: "Project"
    folder: _projects
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{year}}/{{month}}/{{slug}}"
    path: "{{title}}/index"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: project
      - label: Title
        name: title
      - label: Medium
        name: medium
        widget: string
        required: false
      - label: Year
        name: year
        widget: datetime
        dateFormat: MM.YYYY
        format: L
      - label: Curated by
        name: curator
        widget: string
        required: false
      - label: Exhibition/Venue
        name: exhibition
        widget: string
        required: false
      - label: Description
        name: description
        widget: text
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        required: false

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        create: true
        fields:
          - label: Template
            name: template
            widget: hidden
      - file: src/pages/press/index.md
        label: Press
        name: press
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: File
            name: file
            widget: file
          - label: Link
            name: Link
            widget: string
          - label: Tags
            name: tags
            widget: list
