backend:
  name: github
  branch: main
  repo: usrrname/biitsi
  site_url: https://biitsi.org

# global
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: bitsicloud
    api_key: 167316888477451
    multiple: true
media_folder: image/upload
public_folder: static

collections:
  - name: projects
    label: Projects
    label_singular: "Project"
    folder: _projects
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{year}}/{{month}}/{{slug}}"
    path: "{{title}}/index"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: project
      - label: Title
        name: title
      - label: Published on
        name: date
        widget: datetime
        dateFormat: MM.YYYY
        format: L
        required: true
      - label: Description
        name: description
        widget: text
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: press
    label: Press
    label_singular: Press Article
    folder: _press
    create: true
    slug: "{{slug}}"
    preview_path: "_press/{{year}}/{{day}}/{{month}}"
    path: "{{title}}/index"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: markdown
      - label: File
        name: file
        widget: file
        required: false
      - label: Link
        name: Link
        widget: string
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Author/Publication
        name: author
        widget: string
        required: false
      - label: Date
        name: Date
        widget: datetime
        dateFormat: MM.DD.YYYY
        format: L
        required: false

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        create: true
        fields:
          - label: Template
            name: template
            widget: hidden
      - file: src/pages/press/index.md
        label: Press
        name: press
        create: true
        fields:
          - label: Title
            name: title
            widget: string
