backend:
  name: github
  branch: main
  repo: usrrname/biitsi
  site_url: https://biitsi.org

# global
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: biitsicloud
    api_key: 167316888477451
    multiple: true
public_folder: static

collections:
  - name: projects
    label: Projects
    label_singular: "Project"
    folder: "src/pages/_projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: project-post
      - label: Title
        name: title
      - label: Updated On
        name: date
        widget: datetime
        dateFormat: MM.YYYY
        format: L
        required: true
      - label: Description
        name: description
        widget: markdown
        required: false
      - label: Image
        name: image
        widget: file
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: press
    label: Press
    label_singular: Press Article
    folder: src/pages/_press
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: press-post
      - label: Title
        name: title
        widget: string
      - label: Updated On
        name: date
        widget: datetime
        dateFormat: MM.DD.YYYY
        format: L
        required: true
      - label: Description
        name: description
        widget: markdown
      - label: Featured Image
        name: featured image
        widget: image
      - label: File
        name: file
        widget: file
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Year
        name: year
        widget: number
        required: false

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        create: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
      - file: src/pages/press/index.md
        label: Press
        name: press
        fields:
          - label: Title
            name: title
            widget: string
            required: false
      - file: src/pages/tags/index.md
        label: Tags
        name: tags
        fields:
          - label: Title
            name: title
            widget: string
            required: false
